name: iOS Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.44.1"

      - name: Flutter Version
        run: flutter --version

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Clean
        run: flutter clean

      - name: Pub Get
        run: flutter pub get

      - name: Precache iOS
        run: flutter precache --ios

      - name: Print Info.plist
        run: |
          echo "========== INFO.PLIST =========="
          cat ios/Runner/Info.plist

      - name: Print Podfile
        run: |
          echo "========== PODFILE =========="
          cat ios/Podfile

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods

      - name: Install Pods
        working-directory: ios
        run: |
          pod deintegrate || true
          rm -rf Pods
          rm -rf Podfile.lock
          rm -rf .symlinks
          pod repo update
          pod install --repo-update --verbose

      - name: Build iOS
        run: flutter build ios --release --no-codesign

      - name: Upload Runner.app
        uses: actions/upload-artifact@v4
        with:
          name: Runner.app
          path: build/ios/iphoneos/Runner.app
